### ISSUE TITLE
Title Year seems out of place.

### ISSUE THREAD

**Issue by SirDarquan** [unmade/am-date-picker#1]
First, I'd like to say I love the direction you're going with this component. I've been looking for one that does what yours is doing and was getting ready to make one myself. So thanks for putting forth the effort.

That being said, I believe that having the year by itself in the dialog title feels weird. I'm not going to ask you to remove it permanently but could you give us a way to hide it? Or are you planning to make a 'Today' poster like lumX's control with a way to switch between modes? Also, could you center the text in the header?

**Comment by unmade** [comment]
Thank you for your comment.

In a calendar appearance I relied on [Google Material Design Spec](https://www.google.com/design/spec/components/pickers.html#). In my opinion, lumX's header takes too much unnecessary space, so there could be a problem on devices with small screen (for example on iPhone 5s I can't see 'OK' button). The other side is that two different headers with switch between them will make calendar settings too complex. So, I think I'm not going to do this, but if you'd like, I could make the calendar with the header you are asking for in a separate branch . 

To center text and hide year just add this to your stylesheet:

``` css
.am-date-picker__header-current-date h2 {
   line-height: 66px;  /* vertical align */
   text-align: center; /* center text */
}

.am-date-picker__header-current-date p {
   display: none; /* hiding year */
}
```

As for my plans to the future, I'm going to implement responsive design.
